### ISSUE TITLE
[BUG] 新系统需要验证码

### ISSUE THREAD

**Issue by Evyde** [destoryD/JLU_lessons#1]
大佬您好。
新的UIMS系统使用图形验证码，可通过[`https://uims.jlu.edu.cn/ntms/open/get-captcha-image.do?s=1`](https://uims.jlu.edu.cn/ntms/open/get-captcha-image.do?s=1)  (`s=random.randint()`，首次为1)获取。但要求保持在同一会话内。  
另外，登陆时的表单发生变化，由原来的`j_username`和`j_password`变为`username`和`password`，并且验证码需要以`'vcode'`字段提交。  
由于我技术不够，没法对您的代码进行修改，烦请您及时改正。

**Comment by destoryD** [comment]
好的，有时间会研究改进
